name: SSH Connect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # 每天北京时间凌晨7点执行

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko
          pip install requests

      - name: Print current time
        run: date

      - name: Run SSH connection script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS_JSON }}
        run: python ssh.py
